[package]
name = "slog-misc"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[dependencies]
slog = "*"
slog-json = "*"
slog-term = "*"
slog-scope = "*"
slog-scope-stdlog = "*"
slog-syslog = "1.0.0-alpha9"
slog-bunyan= "*"
slog-atomic= "*"
slog-stream = "*"
slog-extra = "*"
slog-stdlog = "*"
slog-envlogger = "*"

log = "0.3.6"
lazy_static = "0.1.16"
nix = "0.6.0"

[replace]
"slog:1.4.0" = { git = "https://github.com/slog-rs/slog" }
"slog-stream:1.2.0" = { git = "https://github.com/slog-rs/stream" }
"slog-term:1.3.5" = { git = "https://github.com/slog-rs/term" }
"slog-extra:0.1.1" = { git = "https://github.com/slog-rs/extra" }
"slog-stdlog:1.1.0" = { git = "https://github.com/slog-rs/stdlog" }
"slog-json:1.2.1" = { git = "https://github.com/slog-rs/json" }
"slog-bunyan:1.1.1" = { git = "https://github.com/slog-rs/bunyan" }
"slog-envlogger:0.5.0" = { git = "https://github.com/slog-rs/envlogger" }
"slog-atomic:0.4.3" = { git = "https://github.com/slog-rs/atomic" }
"slog-scope:0.2.2" = { git = "https://github.com/slog-rs/scope" }
"slog-scope-stdlog:0.2.0" = { git = "https://github.com/slog-rs/scope-stdlog" }
"slog-syslog:1.0.0-alpha9" = { git = "https://github.com/slog-rs/syslog" }
